LM-9715 - Keep Radio & Checkbox Input styling when checked
cignium/hypermedia-client pull request #133
Opened 2022-05-19 17:01 UTC by choquewilber

2022-05-19 17:37 UTC, Edgar-Cordova requested changes

2022-05-19 17:37 UTC, Edgar-Cordova commented on src/components/elements/inputs/boolean-list.js
> +          <div className={cx(className, `ct-${property.display}-option`,
Is className needed here?

2022-05-19 18:11 UTC, choquewilber commented on src/components/elements/inputs/boolean-list.js
> +          <div className={cx(className, `ct-${property.display}-option`,
No, I will remove it

2022-05-19 19:33 UTC, Edgar-Cordova approved these changes

2022-05-24 17:59 UTC, ronaldameri approved these changes

2022-05-31 17:40 UTC, closed without merging